<?php

/**
 * Implements hook_islandora_ingest_steps
 */
/*
function airs_xacml_islandora_ingest_steps(array $form_state) {
  return array(
    'airs_xacml_policy' => array(
      'type'=> 'callback',
      'weight' => 9, 
      'module' => 'airs_xacml',
      'do_function' => array(
        'function' => 'airs_xacml_apply_policy',
        'args' => array(),
      ),
      'undo_function' => array(
        'function' => 'islandora_xacml_editor_undo_policy',
        'args' => array(),
      ),
    ),
  );
}*/

/**
 * Implements hook_islandora_object_ingested
 */
function airs_xacml_islandora_object_ingested($object) {
  dpm($object['MODS']->getContent(''));
  $mods = new SimpleXMLElement($object['MODS']->getContent(''));
  airs_xacml_apply_policy($mods, $object);
}

function airs_xacml_apply_policy($mods, $object) {
  // DECLARATIONS
  global $user;
//  $userAccess = $form_state['islandora']['step_storage']['xml_form_builder_metadata_step']['values']['userAccess'];
//  $contributors = $form_state['islandora']['step_storage']['xml_form_builder_metadata_step']['values']['contributors'];
//  $themes = $form_state['islandora']['step_storage']['xml_form_builder_metadata_step']['values']['themes-tags'];
//  $object = $form_state['islandora']['objects'][0];

  foreach ($mods->accessCondition as $access) {
    switch((string) $access['type']) {
    case 'restriction on access':
      $userAccess = (string)$access;
      break;
    }
  }

  $n=0;
  foreach ($mods->name as $name) {
    switch((string) $name['type']) {
    case 'personal':
      foreach($name->namePart as $namePart) {
        $contributors[$n] = (string)$namePart;
        $n++;
      }
      break;
    }
  }

  $t=0;
  foreach ($mods->genre as $genre) {
    switch((string) $genre['type']) {
    case 'themes':
      $themes[$t] = (string)$genre;
      $t++;
      break;
    }
  }

  dpm($userAccess);
  dpm($contributors);
  dpm($themes); 

  // create new IslandoraXacml object, link it to the object being ingested
  $xacml = new IslandoraXacml($object);

  // allow the user to view and manage the file
  // the administrative role gets this by default
  $xacml->viewingRule->addUser(array($user->name));
  $xacml->managementRule->addUser(array($user->name));

  if ($userAccess != 'User only') {
    // grabs all users listed as collaborators
    foreach ($contributors as $name) {
      $xacml->viewingRule->addUser(array($name));
      $xacml->managementRule->addUser(array($name));
    }

    // use the userAccess field of the form to determine extra permissions
    switch($userAccess) {
      case 'Public':
        $xacml->viewingRule->addRole(array('anonymous user', 'authenticated user'));
        break;

      case 'Registered users':
        $xacml->viewingRule->addRole(array('authenticated user'));
        break;

     /**
      * In the case of 'My sub-theme', if the uploader chooses one of the main
      *  themes (e.g. Theme 1, 2, 3), the file is publicly viewable, with management
      *  permissions for everyone in any subtheme chosen.
      */
      case 'My sub-theme':
        // returns all themes listed in the AIRS Themes field
        foreach ($themes as $theme) {
          // checks if the listing is a string, then if begins with Subtheme or Theme
          if (is_string($theme) && strlen($theme) > 5) {
            if (substr($theme, 0, 8) == 'Subtheme') { 
              $subthemeID = 'st'.substr($theme, 9, 3); 
              $xacml->viewingRule->addRole(array($subthemeID));
              $xacml->managementRule->addRole(array($subthemeID));
            } else if (substr($theme, 0, 5) == 'Theme') {
              $xacml->viewingRule->addRole(array('anonymous user', 'authenticated user'));
            }
          } 
        }
      break;
    }
  }
  // save the policy
  $xacml->writeBackToFedora();
}

function airs_xacml_apply_policy_test($mods) {
  dpm('Definitely in airs_xacml_apply_policy_test()');

  foreach ($mods->accessCondition as $access) {
    switch((string) $access['type']) {
    case 'restriction on access':
      $userAccess = (string)$access;
      break;
    }
  }

  $n=0;
  foreach ($mods->name as $name) {
    switch((string) $name['type']) {
    case 'personal':
      foreach($name->namePart as $namePart) {
        $contributors[$n] = (string)$namePart;
        $n++;
      }
      break;
    }
  }

  $t=0;
  foreach ($mods->genre as $genre) {
    switch((string) $genre['type']) {
    case 'themes':
      $themes[$t] = (string)$genre;
      $t++;
      break;
    }
  }

  dpm($userAccess);
  dpm($contributors);
  dpm($themes);
}


