<?php

include 'includes/airs_xacml.test_cases.inc';

/**
 * @file
 *
 * Module to set XACML policies.
 */

/**
 * Implements hook_xacml_menu()
 */
function airs_xacml_menu() {
  $items = array();
  $forms = array(
    'universal' => 'AIRS Universal',
    'collection' => 'AIRS Collection',
    'citation' => 'AIRS Citation Form',
  );
 
  $items['admin/islandora/airs-xacml-menu'] = array(
    'title' => 'AIRS XACML',
    'description' => 'Oh man. Please.',
    'page callback' => 'drupal_get_form',
    'access arguments' => array('administer site configuration'),
    'page arguments' => array('airs_xacml_admin'),
    'file' => 'includes/airs_xacml.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );

  $items['admin/islandora/airs-form-test'] = array(
    'title' => 'AIRS form test',
    'description' => 'Test page for the AIRS XACML module',
    'page callback' => 'drupal_get_form',
    'access arguments' => array('this is a test'),
    'page arguments' => array($forms['universal']),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Implements hook_form_alter()
 */
function airs_xacml_form_alter(&$form, &$form_state, $form_id) {
  //dsm($form_id); // displays name of forms on the page
  //dsm($form); // displays form information 

  switch($form_id) {
    case 'AIRS Universal':
      //form_alter_permission_box_default_value_setting($form, 'Registered users');

      $form['submit'] = array(
	'#type' => 'submit',
	'#value' => t('Submit'),
	'#weight' => 20,
	'#submit' => array('airs_xacml_form_submit'),
      );
      break;

    case 'AIRS Collection':
      dsm(t('This is the AIRS Collection form'));
      break;

    case 'AIRS Citation Form':
      dsm(t('This is the AIRS Citation Form'));
      break;
/*
    case 'xml_form_builder_ingest_form':
      array_push($form['next']['#submit'], array(
        'callback' => 'airs_xacml_form_submit', 
      ));
      break;
*/
  }
}

/**
 * Implements hook_islandora_ingest_steps_alter().
 */
function airs_xacml_islandora_ingest_steps_alter(&$steps, &$form_state) {
  if (isset($steps['xml_form_builder_metadata_step'])) {
    $metadata_step_storage = islandora_ingest_form_get_step_storage($form_state, 'xml_form_builder_metadata_step');
    if (isset($metadata_step_storage['association']) && $metadata_step_storage['association']['dsid'] == 'MODS') {
      airs_xacml_form_submit($form_state);
    } 
  }
}

/**
 * airs_xacml_form_submit()
 *
 * This function is used as the submit handler for the
 * AIRS Universal form
 */
function airs_xacml_form_submit(array &$form_state) {

  if (isset($form_state['values']['userAccess']))
    $userAccess = $form_state['values']['userAccess'];
  else
    $userAccess = '';

  switch ($userAccess) {
    case 'Public':
    //public_airs_xacml_form_submit($form_state);
      if (isset($form_state['values']['userAccess'])) {
        public_airs_xacml_form_submit($form_state);
        //dsm($form_state['values']['userAccess']);
      }
      break;
    case 'Registered users':
      registered_airs_xacml_form_submit();
      break;
    case 'My sub-theme':
      sub_theme_airs_xacml_form_submit();
      break;
    case 'Specific users':
      specific_airs_xacml_form_submit();
      break;
    case 'User only':
      user_airs_xacml_form_submit();
      break;
    default:
      dsm(t('ain\'t nuthin'));
      break;
  }
}

/**
 * userAccess_airs_xacml_form_submit() ftns
 * 
 * One of these functions is called based on the decision
 *  in the switch block of airs_xacml_form_submit().
 */

function public_airs_xacml_form_submit(array &$form_state) {
  dsm(t('ftn called: public_airs_xacml_form_submit()')); 
  dsm($form_state['values']['userAccess']);
  dsm($form_state);
}

function registered_airs_xacml_form_submit() {
  dsm(t('ftn called: registered_airs_xacml_form_submit()'));
}

function sub_theme_airs_xacml_form_submit() {
  dsm(t('ftn called: sub_theme_airs_xacml_form_submit()'));
}

function specific_airs_xacml_form_submit() {
  dsm(t('ftn called: specific_airs_xacml_form_submit()'));
}

function user_airs_xacml_form_submit() {
  dsm(t('ftn called: user_airs_xacml_form_submit()'));
}
